#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset

if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}" 
fi

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

python << END
import sys
import time
import psycopg

suggest_unrecoverable_after = 30
start_time = time.time()
while True:
    try:
        psycopg.connect(
            dbname="${POSTGRES_DB}", 
            user="${POSTGRES_USER}", 
            password="${POSTGRES_PASSWORD}", 
            host="${POSTGRES_HOST}", 
            port="${POSTGRES_PORT}",
        )
        break
    except psycopg.OperationalError as e:
        current_time = time.time()
        if current_time - start_time > suggest_unrecoverable_after:
            sys.stderr.write(f"This is taking longer than expected. The following exception may be indicative of an unrecoverable error: {e}\n")

    time.sleep(1)
END

>&2 echo "Postgres is available"

exec "$@"