version: "3.9"

services:
  django-backend:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    volumes:
      - .:/app:z
      - type: volume
        source: static-volume
        target: /app/staticfiles
      - type: volume
        source: media-volume
        target: /app/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - postgres
      - mailhog
    command: /start
    networks:
      - blogorie-backend-network

  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    volumes:
      - type: volume
        source: local_postgres_data
        target: /var/lib/postgresql/data
      - type: volume
        source: local_postgres_data_backup
        target: /backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - blogorie-backend-network

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"
    networks:
      - blogorie-backend-network

networks:
  blogorie-backend-network:
    driver: bridge

volumes:
  static-volume:
  media-volume:
  local_postgres_data: {}
  local_postgres_data_backup: {}